name: ubx_vinne_admin_web
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.2
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  pretty_dio_logger: ^1.1.1
  logger: ^1.1.0
  flutter_screenutil: ^5.4.0+1
  dart_std: ^0.0.4
  flutter_svg: ^1.0.3
  bot_toast: ^4.0.1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  flutter_lints: ^1.0.4
  retrofit_generator:
  mockito:


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
